apiVersion:   v1 
kind:   Service   #  service is not equals to Service  
metadata:
  name: class24 
spec: 
  selector:
    app:  nginx 
  type: ClusterIP #[ NodePort, LoadBalancer]
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP 