apiVersion:   v1 
kind:   Service   #  service is not equals to Service  
metadata:
  name: class24-np 
spec: 
  selector:
    app:  nginx 
  type: NodePort        #[ NodePort, LoadBalancer]
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30040
    protocol: TCP 