apiVersion:   v1 
kind:   Service   #  service is not equals to Service  
metadata:
  name: class24-lb
spec: 
  selector:
    app:  nginx 
  type: LoadBalancer         #[ClusterIP,  NodePort, LoadBalancer]
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30045
    protocol: TCP 